In [1]:
# Open Database

import pandas as pd
import numpy as np

from sqlalchemy import create_engine

sqlitedb_abs_path = '/vagrant/Data/raw_data_project_m1.db'

conn_str = f'sqlite:///{sqlitedb_abs_path}'

engine = create_engine(conn_str)

pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", engine)

#Call all tables

            name
0  personal_info
1   country_info
2    career_info
3      poll_info

In [2]:
# Create dataframe from db query to get uuid, Gender and Age

working_dataframe = pd.read_sql_query('''SELECT career_info.normalized_job_code, personal_info.gender, personal_info.age, country_info.country_code
FROM personal_info
JOIN career_info ON career_info.uuid = personal_info.uuid 
JOIN country_info ON personal_info.uuid = country_info.uuid ;  ''', engine)

working_dataframe

                   normalized_job_code  gender           age country_code
0                                 None    male  61 years old           AT
1     861a9b9151e11362eb3c77ca914172d0    male  57 years old           AT
2                                 None    male  32 years old           AT
3     049a3f3a2b5f85cb2971ba77ad66e10c    Male  45 years old           AT
4     f4b2fb1aa40f661488e2782b6d57ad2f     Fem  41 years old           AT
...                                ...     ...           ...          ...
9644  847165cfda6b1dc82ae22b967da8af2f  FeMale  37 years old           SK
9645  a4d5b8b38f9513825d0d94a981ebe962    Male  53 years old           SK
9646                              None    male          1992           SK
9647  775190277a849cba701b306a7b374c0a    male  47 years old           SK
9648  8a7a3f1bce0958ae9f090683e5a925b7  FeMale  51 years old           SK

[9649 rows x 4 columns]

In [3]:
## Clean up gender

gender = working_dataframe['gender'].to_list()
clean_gender = []

for item in gender:
    if "fem" in item.lower():
        clean_gender.append("Female")
    else:
        clean_gender.append("Male")
        
working_dataframe['gender'] = clean_gender

working_dataframe

                   normalized_job_code  gender           age country_code
0                                 None    Male  61 years old           AT
1     861a9b9151e11362eb3c77ca914172d0    Male  57 years old           AT
2                                 None    Male  32 years old           AT
3     049a3f3a2b5f85cb2971ba77ad66e10c    Male  45 years old           AT
4     f4b2fb1aa40f661488e2782b6d57ad2f  Female  41 years old           AT
...                                ...     ...           ...          ...
9644  847165cfda6b1dc82ae22b967da8af2f  Female  37 years old           SK
9645  a4d5b8b38f9513825d0d94a981ebe962    Male  53 years old           SK
9646                              None    Male          1992           SK
9647  775190277a849cba701b306a7b374c0a    Male  47 years old           SK
9648  8a7a3f1bce0958ae9f090683e5a925b7  Female  51 years old           SK

[9649 rows x 4 columns]

In [4]:
# cleaning age

age = working_dataframe['age'].to_list()
clean_age = []

for item in age:
    if 'old' in item:
        clean_age.append(int(item[0:2]) + 4) 
    else:
        clean_age.append(2020 - int(item) + 4)

working_dataframe['age'] = clean_age

working_dataframe

                   normalized_job_code  gender  age country_code
0                                 None    Male   65           AT
1     861a9b9151e11362eb3c77ca914172d0    Male   61           AT
2                                 None    Male   36           AT
3     049a3f3a2b5f85cb2971ba77ad66e10c    Male   49           AT
4     f4b2fb1aa40f661488e2782b6d57ad2f  Female   45           AT
...                                ...     ...  ...          ...
9644  847165cfda6b1dc82ae22b967da8af2f  Female   41           SK
9645  a4d5b8b38f9513825d0d94a981ebe962    Male   57           SK
9646                              None    Male   32           SK
9647  775190277a849cba701b306a7b374c0a    Male   51           SK
9648  8a7a3f1bce0958ae9f090683e5a925b7  Female   55           SK

[9649 rows x 4 columns]

In [5]:
#retrieving job code

import requests
import json

#first get unique values
unique_values_job = working_dataframe['normalized_job_code'].unique()


#getting job data from Api
jobs_id = []
counter = 0
for code in unique_values_job:
    response = requests.get(f'http://api.dataatwork.org/v1/jobs/{code}')
    jobs_id.append(response.json())
    counter +=1
    if counter % 10 == 0:
        print(counter)

#Create Dataframe from results
job_title_df = pd.DataFrame.from_records(jobs_id[1:]).drop(columns=['normalized_job_title', 'parent_uuid'])

job_title_df

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150

                                 uuid                              title
0    861a9b9151e11362eb3c77ca914172d0  Automatic Data Processing Planner
1    049a3f3a2b5f85cb2971ba77ad66e10c                   Data Coordinator
2    f4b2fb1aa40f661488e2782b6d57ad2f                 Database Developer
3    27af8700f5577cec835acee2cb90a2ff              Data Entry Specialist
4    c1b670eba9ccb65e7c99f7da116d5b9c                 Database Architect
..                                ...                                ...
151  b0fa6ede410f50b82ab74f5a705fe699              Analytical Data Miner
152  559a21f836c93876f31b60e6d10656a7            Data Analysis Assistant
153  c1fb1a01b78373ac2153c66fa08d16dc             Data Examination Clerk
154  05bb9a333a66d6eb151e253623efe1c0                   Data Entry Clerk
155  4cee16550636e292b8d136486fce943b                 Data Capture Clerk

[156 rows x 2 columns]

In [6]:
# Get normalized_job_title list

normalized_job_codes = working_dataframe['normalized_job_code'].to_list()
available_job_codes = job_title_df.to_dict('records')
job_titles = []



# Add title to working dataframe by joining the uuids from both dataframes
for code in normalized_job_codes:
    # Query the job title DF so it returns the uuid for the current row
    # normalized job code in the working dataframe
    if code == None:
        job_titles.append(None)
    else:
        for row in available_job_codes:
            if row['uuid'] == code:
                job_titles.append(row['title'])

# Add title column to the working dataframe
working_dataframe['title'] = job_titles

working_dataframe

,normalized_job_code,gender,age,country_code,title
0,None,Male,65,AT,None
1,861a9b9151e11362eb3c77ca914172d0,Male,61,AT,Automatic Data Processing Planner
2,None,Male,36,AT,None
3,049a3f3a2b5f85cb2971ba77ad66e10c,Male,49,AT,Data Coordinator
4,f4b2fb1aa40f661488e2782b6d57ad2f,Female,45,AT,Database Developer
...,...,...,...,...,...
9644,847165cfda6b1dc82ae22b967da8af2f,Female,41,SK,Data Warehouse Developer
9645,a4d5b8b38f9513825d0d94a981ebe962,Male,57,SK,Database Manager
9646,None,Male,32,SK,None
9647,775190277a849cba701b306a7b374c0a,Male,51,SK,Data Officer
9648,8a7a3f1bce0958ae9f090683e5a925b7,Female,55,SK,Data Scientist

In [7]:
available_job_codes

[{'uuid': '861a9b9151e11362eb3c77ca914172d0',
  'title': 'Automatic Data Processing Planner'},
 {'uuid': '049a3f3a2b5f85cb2971ba77ad66e10c', 'title': 'Data Coordinator'},
 {'uuid': 'f4b2fb1aa40f661488e2782b6d57ad2f', 'title': 'Database Developer'},
 {'uuid': '27af8700f5577cec835acee2cb90a2ff',
  'title': 'Data Entry Specialist'},
 {'uuid': 'c1b670eba9ccb65e7c99f7da116d5b9c', 'title': 'Database Architect'},
 {'uuid': 'd71c4164c99a5f9bca773e755a72f40f',
  'title': 'Geographic Information Systems Database Administrator (GIS Database Administrator)'},
 {'uuid': '2ee80cf30e2483dfe0947adc0428f8c5',
  'title': 'Crime Data Specialist'},
 {'uuid': '897ef18a9321616495831a4b4b0c1bb2',
  'title': 'Data Communications Software Consultant'},
 {'uuid': 'a003702c0cea282e17967772dd83de5e',
  'title': 'Data Security Analyst'},
 {'uuid': '04c82eae29e1c4a30eac0710b74ab276',
  'title': 'Database Marketing Analyst'},
 {'uuid': 'fcaf4aac737e53ad24b9f32f08b8740f',
  'title': 'Computer or Data Processing Systems Consultant'},
 {'uuid': '3833bd699e7afe4665b595f282da0387',
  'title': 'Database Development and Administration Project Manager'},
 {'uuid': '19e384e977796c25780d8c28b12089c4',
  'title': 'Naval Tactical Data System--Combat Information Center Watch Officer, General'},
 {'uuid': '474b962c13632a04e42a546be4f11dbb', 'title': 'Data Coder Operator'},
 {'uuid': 'dac2e921c1f887d9efc4c06fa33c1397',
  'title': 'Automatic Data Processing Customer Liaison (ADP Customer Liaison)'},
 {'uuid': '996da29c84f5eed00da40c230f4c4078',
  'title': 'Data Entry Representative'},
 {'uuid': 'cc2b26cc436bea36bda3bdd7367c411a',
  'title': 'Data Processing Auditor'},
 {'uuid': '25fe195cbf915c0824fa6c44e6d0008c',
  'title': 'Maintenance Data Analyst'},
 {'uuid': '76385cb24e831b3364279b9de5641d8f',
  'title': 'Automatic Data Processing Systems Security Specialist (ADP Systems Security)'},
 {'uuid': '16b67d7f57698455aefbc1ae1b358b50', 'title': 'Database Engineer'},
 {'uuid': 'b24ece3300d2f8ab34f9553e531183d6',
  'title': 'Data Processing Systems Project Planner'},
 {'uuid': '5db2c8d6539f983e1ca3d7c5b939e190',
  'title': 'Database Administration Associate'},
 {'uuid': '36675c937946c8a4fc5de7d0b4c850de',
  'title': 'Data Warehousing Engineer'},
 {'uuid': '847165cfda6b1dc82ae22b967da8af2f',
  'title': 'Data Warehouse Developer'},
 {'uuid': '2ca138b991c50dc6696238e5ad800142',
  'title': 'Database Software Technician'},
 {'uuid': '775190277a849cba701b306a7b374c0a', 'title': 'Data Officer'},
 {'uuid': '022d0e3a40aa3e29bca6851542b27842', 'title': 'Data Keyer'},
 {'uuid': '375017ea3a1a97f5ea676def873bb25b',
  'title': 'Geographic Information Systems Data Specialist (GIS Data Specialist)'},
 {'uuid': '1dd2fdc8a3981f2a1d8f0ca173952bb8',
  'title': 'Database Administration Manager'},
 {'uuid': 'e605336f5a43949cb6b18054fd1937f1',
  'title': 'Database Security Expert'},
 {'uuid': '800b621aab5dac18f4caef621fa43a49', 'title': 'Data Systems Manager'},
 {'uuid': 'd06dfb43c95b585a89ae556c9221b573',
  'title': 'Data Warehousing Manager'},
 {'uuid': 'a12a16280e22220f9354333f6fe1b22a',
  'title': 'Geographic Information Systems Data Administrator (GIS Data Administrator)'},
 {'uuid': '477b53ef09d37f098d5ed74f47fcbaec',
  'title': 'Data Base Design Analyst'},
 {'uuid': 'e2f68bf748aea2c7d2254550c0c92b23',
  'title': 'Director of Data Operations'},
 {'uuid': '45033f83b6e0309eca9bcd76917f15d0', 'title': 'Database Modeler'},
 {'uuid': '141ddda0f613da65a280521247de0e9f', 'title': 'Data Administrator'},
 {'uuid': '3ddea1b52e520996e4ec9fb70dc8b86b',
  'title': 'Field Artillery Automated Tactical Data System Specialist'},
 {'uuid': '6408c0d7c7faa4ced47fbc8474698126',
  'title': 'Database Design Analyst'},
 {'uuid': '07b7555fa790debaf5b04d1409ad5f11',
  'title': 'Database Security Administrator'},
 {'uuid': 'a4d5b8b38f9513825d0d94a981ebe962', 'title': 'Database Manager'},
 {'uuid': '5e93fd1a58c8a67b295f69d87d1a940d',
  'title': 'Geographic Information Systems Data Manager (GIS Data Manager)'},
 {'uuid': '122f24bc911a79c26ca66210557dda07',
  'title': 'Clinical Data Specialist'},
 {'uuid': '76b0ba6af40991629e20dff36edd02a5',
  'title': 'Data Management Information Technology Specialist'},
 {'uuid': '970eb38c7b3eb080466052ea994af189',
  'title': 'Internet Database Specialist'},
 {'uuid': 'cf2d4db3c258faa2499bdeeeed6721a5',
  'title': 'GPS Field Data Collector (Global Positioning System Field Data Collector)'},
 {'uuid': '90c5430dbc810aec8695af2f1f4c42e8',
  'title': 'Electronic Data Processing Auditor (EDP Auditor)'},
 {'uuid': '7bb15eefb19ed09c59349baad7e8469e', 'title': 'Database Coordinator'},
 {'uuid': 'ec3d88b2fd083b870b8c5a603898ed39',
  'title': 'Databases Computer Consultant'},
 {'uuid': '1f8576bdffa64f492405d02b842c41a6',
  'title': 'Data Management Associate'},
 {'uuid': 'edc64316da9707432443c7a4461abe6c',
  'title': 'Data Security Administrator'},
 {'uuid': '6cf4d336112984368f83181ac5ffe948', 'title': 'Health Data Analyst'},
 {'uuid': 'd4624ed8068d24948e18303212593cd6', 'title': 'Data Architect'},
 {'uuid': '1a281bf4bd1fe9b2a6e464e508bea167',
  'title': 'Data Storage Specialist'},
 {'uuid': '2f704538f6c9d6459a97314be98124e2', 'title': 'Data Collector'},
 {'uuid': '3161063d378eecc4581c5cdee46a2a6c',
  'title': 'Head of Information Systems and Data Processing'},
 {'uuid': '781f5d3a80812531fdc81125a527a626',
  'title': 'Data Warehouse Specialist'},
 {'uuid': '38a15ceadcdd6d4db16a88fa1a72b083',
  'title': 'Data Warehouse Analyst'},
 {'uuid': 'e55556364d2096578fd153e9800e826f', 'title': 'Database Consultant'},
 {'uuid': 'd24ffac92c24fb0e7bd1abc5fc3b6254', 'title': 'Data Manager'},
 {'uuid': 'ccd7528fb38f16077360c5b67c9700c4',
  'title': 'Data Communications Analyst'},
 {'uuid': 'f6fbd9dea1fa8f899683ade8e7d87d60', 'title': 'Data Entry Associate'},
 {'uuid': '0de6170ccbed08e62b2e5862d5846a43', 'title': 'Database Tester'},
 {'uuid': '499f9d9b6722342608656559b15abd90',
  'title': 'Clinical Data Associate'},
 {'uuid': '8a7a3f1bce0958ae9f090683e5a925b7', 'title': 'Data Scientist'},
 {'uuid': '7acaed29536648e45ea2b82d45047fcf', 'title': 'Medical Data Analyst'},
 {'uuid': '02e4c028f64f176de2f54bbc2f5403ce',
  'title': 'Marketing Database Analyst'},
 {'uuid': '569da68cdcac43a3b4a0126ea9170570', 'title': 'Database Designer'},
 {'uuid': 'ced804d972b03cca6d523ec8925a7943',
  'title': 'Oracle Database Administrator (Oracle DBA)'},
 {'uuid': '41b2978a2c07c5f477e60f26372d6c85',
  'title': 'Database Management System Specialist (DBMS Specialist)'},
 {'uuid': 'd9e964a222fdd9527319ad88adbfaa2e',
  'title': 'SQL Database Administrator'},
 {'uuid': 'ac47656fd51c2cd8037057262c910dc4',
  'title': 'Data Processing Manager'},
 {'uuid': 'e49986dae76619a3941d280ee14d38ae', 'title': 'Data Miner'},
 {'uuid': 'f842344417ed2fc226d9cc00f9562458', 'title': 'Log Data Technician'},
 {'uuid': '096536ec43ce2a7de73031b271a1c132',
  'title': 'Flight Data Technician'},
 {'uuid': 'a33662485eb4ad97096183db945308f4',
  'title': 'Automatic Data Processing Planner (ADP Planner)'},
 {'uuid': '4f75f97ac5b5f00f9420074d501f0803',
  'title': 'Data Capture Specialist'},
 {'uuid': 'f36c6ada3a808453a0bf241c74a4e994',
  'title': 'Reference Data Expert'},
 {'uuid': '41ba88cfd476ee8d5e3d9f7cea62f051',
  'title': 'Data Recovery Planner'},
 {'uuid': '894ca61c22718617c7e2404f582153da',
  'title': 'Data Processing Consultant'},
 {'uuid': '34d80517fe3bc143f9fc850386b8ffd7',
  'title': 'Clinical Data Coordinator'},
 {'uuid': 'e7b3e1c6a32c7247cd4857e4c3574165',
  'title': 'Data Processing Systems Analyst'},
 {'uuid': '36ac256201657eeaa67ee95aaae3cd54',
  'title': 'Data Warehousing Specialist'},
 {'uuid': 'bc6dcc49557388a9f53d6e642e73d7a2',
  'title': 'Business Database Analyst'},
 {'uuid': '00bff17fca67555d8d86e8ead86dcd70', 'title': 'Database Analyst'},
 {'uuid': 'b42566382f2d3deeca56d3667004fc9e', 'title': 'Data Center Manager'},
 {'uuid': '7932d4705d002b47789c11edfaed685e',
  'title': 'Data Control Assistant'},
 {'uuid': 'aee597cd78f235c9db9d3ca987c7c846',
  'title': 'Database Development Project Manager'},
 {'uuid': '1c37a6e2bf157c0eff4665c57c52602d',
  'title': 'SCADA Technician (Supervisory Control and Data Acquisition Technician)'},
 {'uuid': '46b09f5f86f1ed46a8cb8e14d41418c7',
  'title': 'Survey Data Technician'},
 {'uuid': 'a2a9fbe67b4aa2b551ba0f3adac90a99',
  'title': 'Engineer, System Electronic Data Processing (Engineer, System EDP)'},
 {'uuid': '77d124811ae6887bd4ff42b0e2b49116',
  'title': 'Data Warehouse Architect'},
 {'uuid': 'f05d2014d4a9adaab50fa1e0ca6f6c8c',
  'title': 'Naval Tactical Data System--Combat Information Center Watch Officer, Carrier Controlled Approach Controller'},
 {'uuid': 'ac2588d5d7676a49bdcd038e4a0a0ec5', 'title': 'Data Compiler'},
 {'uuid': '2173ff3afd8d28192f7cf119af201940',
  'title': 'Data Modeling Specialist'},
 {'uuid': 'f5bc91b67dc30ad204158092116c4ed2',
  'title': 'Clinical Data Manager'},
 {'uuid': '433df1b945d32f17d9e61cf60a9bd06e', 'title': 'Data Abstractor'},
 {'uuid': '1295a187473fd2f53427769fc7a4c02e',
  'title': 'Clinical Data Management Associate Director'},
 {'uuid': '004431b0c1ce29ff6145307fa23f3f98',
  'title': 'Data Reduction Technician'},
 {'uuid': '8fd068c8d9be73abfa678856177b6c40',
  'title': 'Data Operations Director'},
 {'uuid': 'c34f03aa0a9c6edbe8ec50f4fa3687a8', 'title': 'Data Center Operator'},
 {'uuid': '7aecc34a90868aac810bf3693b11534e',
  'title': 'Clinical Trials Data Coordinator'},
 {'uuid': '086f0063610283d1c23c44bca4ef92c0',
  'title': 'Database Administrator (DBA)'},
 {'uuid': '16b49a63ac3fcb90356c30187110ed94',
  'title': 'Data Processing Auxiliary Equipment Operator'},
 {'uuid': '437e4414c78611a270a5cedb4b4c0eed',
  'title': 'Data Collection Technician'},
 {'uuid': '679fb7003e0aedc14891fcd15dd846c5', 'title': 'Database Specialist'},
 {'uuid': '7a37ddb38441873334fd8ff07c17ad22',
  'title': 'Data Acquisition Technician'},
 {'uuid': '58eaf730050d2e23c7361fbb782e30a2',
  'title': 'Data Processing Mechanic'},
 {'uuid': 'd0abc47e83e7d85921e113f85175547a',
  'title': 'Data Sciences Director'},
 {'uuid': '73d251075a710326ae436d9819246377',
  'title': 'Databases Software Consultant'},
 {'uuid': '5e2bfe1fb8451158ff488c673535980c',
  'title': 'Data Entry Machine Operator'},
 {'uuid': 'ac9f868b5c3e7cb3f31bcead5dadeb71',
  'title': 'Micro Computer Data Processor'},
 {'uuid': 'f670246beda8187fbe875401e7bc4ba6',
  'title': 'Data Processing Services Sales Representative'},
 {'uuid': '0044971fda4a261b6049a63817913e95',
  'title': 'Data Processing Equipment Repairer'},
 {'uuid': 'b36bc5f02fd641a126df999bcefa2777', 'title': 'Data Technician'},
 {'uuid': '067c85859a63aa6f1c8c936904124dd6',
  'title': 'Naval Tactical Data System--Combat Information Center Officer'},
 {'uuid': '491d82be40d8395e347f9584124bccdd',
  'title': 'Flight Test Data Acquisition Technician'},
 {'uuid': '7028f15ad274cb4d9505101b9c1306b1',
  'title': 'Clinical Data Management Manager (CDM Manager)'},
 {'uuid': 'fd69391dc29c83d5ad744daa57de0175', 'title': 'Data Transcriber'},
 {'uuid': '3def30a9bc4356164176ba909f40bab8', 'title': 'Data Input Clerk'},
 {'uuid': '132aa9e82c5d4c8a395342d0a6e22c5c',
  'title': 'Electronic Data Interchange System Developer (EDI System Developer)'},
 {'uuid': '07b2ace822aff5d35dcf5ea264ef3b59',
  'title': 'Database Administration Project Manager'},
 {'uuid': 'f8984e50675cf61e5ac1ea8f661e0ab2',
  'title': 'Field Traffic Data Technician'},
 {'uuid': 'd329d187dafb7546061ec7fbf137a2b4',
  'title': 'Clinical Data Abstractor'},
 {'uuid': 'd63e35f948115e0c328a49db7bdb6e59',
  'title': 'Data Control Clerk Supervisor'},
 {'uuid': 'bf7f43295d45cdced048c8126f977b6b', 'title': 'Datastage Developer'},
 {'uuid': '6bf4290b983d58ce153af610008846c9',
  'title': 'Data Entry Technician'},
 {'uuid': 'f1fc61f279e3ad14863e582ca6fdc473',
  'title': 'Clinical Data Analyst'},
 {'uuid': '31bf3181813e21ffdfd76b5881fab066',
  'title': 'Data Entry Supervisor'},
 {'uuid': '04b0eaf624b2deb45ccd62cf6ec7c7bc',
  'title': 'Data Conversion Operator'},
 {'uuid': '2616d64becb4f2c478dd42f501bbfbff',
  'title': 'Data Processing Control Clerk'},
 {'uuid': '776bf47111206d31ccf835650e1054cc', 'title': 'Data Typist'},
 {'uuid': 'c3b5ebd7b88c20786f11e87846c7d6ae',
  'title': 'SCADA Operator (Supervisory Control and Data Acquisition Operator)'},
 {'uuid': 'dfea9e8bc3c565ff9e64d4288b1c423d',
  'title': 'Customer Data Technician'},
 {'uuid': 'a50d1f4be063829950e6ddb02c91379f', 'title': 'Database Programmer'},
 {'uuid': 'af6630abd24c19f77cfba94aa4e3b7e1', 'title': 'Data Specialist'},
 {'uuid': '901740e84d1a4760e440b039adac9df2',
  'title': 'Data Processing Clerk'},
 {'uuid': 'f2ecf36d7eb0a4225974fc6c4f48cfcb',
  'title': 'Voice and Data Technician'},
 {'uuid': 'f1fb62e4c97f4f5cd5001877cb94379e', 'title': 'Data Processor'},
 {'uuid': 'b9a57264eaada670703db113483ddfc3', 'title': 'Data Modeler'},
 {'uuid': '65b92572bca68ff9c49c930749fa348c', 'title': 'LiDAR Data Analyst'},
 {'uuid': '59dab7d0a3ee97d939aa8b1a8deec857',
  'title': 'Data Management Manager'},
 {'uuid': 'afea0e0169a98ee264db2ddb1c6e6a34',
  'title': 'Data Processing Supervisor'},
 {'uuid': '0facaffe51cc1998a5fbdbe5fd18fd98',
  'title': 'Weight in Motion Field Data Collection Technician'},
 {'uuid': 'ccf2c4daae069f054cada4c911819a17',
  'title': 'Scientific Database Curator'},
 {'uuid': '1426c924e1b6b162f6bfdd1906d98d0e',
  'title': 'Operations Officer, Afloat (Naval Tactical Data Systems)'},
 {'uuid': 'eb3d789747d52df803ce63fe37bf53e9', 'title': 'Data Analyst'},
 {'uuid': 'bdf4dcd92089bc17345de83f4d06090f', 'title': 'Data Entry Operator'},
 {'uuid': '5285758deb04c98f58cbae2747195f33', 'title': 'Data Reviewer'},
 {'uuid': '04c27c76b463a917800549cf88a59961',
  'title': 'Data Communications Technician'},
 {'uuid': '631bc3a12ed11340fc94ebfffa8f5f4e', 'title': 'Database Technician'},
 {'uuid': 'b0fa6ede410f50b82ab74f5a705fe699',
  'title': 'Analytical Data Miner'},
 {'uuid': '559a21f836c93876f31b60e6d10656a7',
  'title': 'Data Analysis Assistant'},
 {'uuid': 'c1fb1a01b78373ac2153c66fa08d16dc',
  'title': 'Data Examination Clerk'},
 {'uuid': '05bb9a333a66d6eb151e253623efe1c0', 'title': 'Data Entry Clerk'},
 {'uuid': '4cee16550636e292b8d136486fce943b', 'title': 'Data Capture Clerk'}]

In [8]:
# Now web scraping to get the countries.
# First, install the library Beautiful Soup

!pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in /home/vagrant/miniconda3/envs/ironhack_env/lib/python3.8/site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2 in /home/vagrant/miniconda3/envs/ironhack_env/lib/python3.8/site-packages (from BeautifulSoup4) (2.1)

In [9]:
import requests

url = 'https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes'
html = requests.get(url).content
html[:5000]

b'\xef\xbb\xbf<!DOCTYPE html>\n<html lang="en" dir="ltr" class="client-nojs">\n<head>\n<meta http-equiv="X-UA-Compatible" content="Ie=Edge,chrome=1"/> <meta charset="UTF-8" /><title>Glossary:Country codes - Statistics Explained</title>\n<meta name="generator" content="MediaWiki 1.22.5" />\n<link rel="shortcut icon" href="https://ec.europa.eu/eurostat/estat-theme/images/favicon.ico" />\n<link rel="search" type="application/opensearchdescription+xml" href="/eurostat/statistics-explained/opensearch_desc.php" title="Statistics Explained (en)" />\n<link rel="EditURI" type="application/rsd+xml" href="https://ec.europa.eu/eurostat/statistics-explained/api.php?action=rsd" />\n<link rel="alternate" type="application/atom+xml" title="Statistics Explained Atom feed" href="/eurostat/statistics-explained/index.php?title=Special:RecentChanges&amp;feed=atom" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=ext.rtlcite&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.shared&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=skins.statexpflat&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<meta name="ResourceLoaderDynamicStyles" content="" />\n<link rel="stylesheet" href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=statexpflat&amp;*" />\n<style>a:lang(ar), a:lang(ckb), a:lang(kk-arab), a:lang(mzn), a:lang(ps), a:lang(ur) { text-decoration: none; }</style>\n\n<script src="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=statexpflat&amp;*"></script>\n<script>if(window.mw){\nmw.config.set( {\n    "wgCanonicalNamespace": "Glossary",\n    "wgCanonicalSpecialPageName": false,\n    "wgNamespaceNumber": 100,\n    "wgPageName": "Glossary:Country_codes",\n    "wgTitle": "Country codes",\n    "wgCurRevisionId": 512615,\n    "wgRevisionId": 512615,\n    "wgArticleId": 1994,\n    "wgIsArticle": true,\n    "wgIsRedirect": false,\n    "wgAction": "view",\n    "wgUserName": null,\n    "wgUserGroups": [\n        "*"\n    ],\n    "wgCategories": [\n        "Geography glossary",\n        "Glossary"\n    ],\n    "wgBreakFrames": false,\n    "wgPageContentLanguage": "en",\n    "wgPageContentModel": "wikitext",\n    "wgSeparatorTransformTable": [\n        "",\n        ""\n    ],\n    "wgDigitTransformTable": [\n        "",\n        ""\n    ],\n    "wgDefaultDateFormat": "dmy",\n    "wgMonthNames": [\n        "",\n        "January",\n        "February",\n        "March",\n        "April",\n        "May",\n        "June",\n        "July",\n        "August",\n        "September",\n        "October",\n        "November",\n        "December"\n    ],\n    "wgMonthNamesShort": [\n        "",\n        "Jan",\n        "Feb",\n        "Mar",\n        "Apr",\n        "May",\n        "Jun",\n        "Jul",\n        "Aug",\n        "Sep",\n        "Oct",\n        "Nov",\n        "Dec"\n    ],\n    "wgRelevantPageName": "Glossary:Country_codes",\n    "wgIsProbablyEditable": false,\n    "wgRestrictionEdit": [],\n    "wgRestrictionMove": [],\n    "wgWikiEditorEnabledModules": {\n        "toolbar": true,\n        "dialogs": false,\n        "hidesig": true,\n        "templateEditor": false,\n        "templates": false,\n        "preview": false,\n        "previewDialog": false,\n        "publish": false,\n        "toc": false\n    },\n    "wgCategoryTreePageCategoryOptions": "{\\"mode\\":0,\\"hideprefix\\":20,\\"showcount\\":true,\\"namespaces\\":false}"\n} );\n}</script><script>if(window.mw){\nmw.loader.implement( "user.options", function () {\nmw.user.options.set( {\n    "ccmeonemails": 0,\n    "cols": 80,\n    "date": "default",\n    "diffonly": 0,\n    "disablemail": 0,\n    "disablesuggest": 0,\n    "editfont": "default",\n    "editondblclick": 0,\n    "editsection": 1,\n    "editsectiononrightclick": 0,\n    "enotifminoredits": 0,\n    "enotifrevealaddr": 0,\n    "enotifusertalkpages": 1,\n    "enotifwatchlistpages": 1,\n    "extendwatchlist": 0,\n    "fancysig": 0,\n    "forceeditsummary": 0,\n    "gender": "unknown",\n    "hideminor": 0,\n    "hidepatrolled": 0,\n    "imagesize": 2,\n    "justify": 0,\n    "math": 6,\n    "minordefault": 0,\n    "newpageshidepatrolled": 0,\n    "nocache": 0,\n    "noconvertlink": 0,\n    "norollbackdiff": 0,\n    "numberheadings": 0,\n    "previewonfirst": 0,\n    "previewontop": 1,\n    "rcdays": 7,\n    "rclimit": 50,\n    "rememberpassword": 0,\n    "rows": 25,\n    "searchlimit": 20,\n    "showhiddencats": 0,\n    "shownumberswatching": 1,\n    "showtoc": 1,\n    "showtoolbar": 1,\n   '

In [10]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'html.parser')

soup

<!DOCTYPE html>

<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta content="Ie=Edge,chrome=1" http-equiv="X-UA-Compatible"/> <meta charset="utf-8"/><title>Glossary:Country codes - Statistics Explained</title>
<meta content="MediaWiki 1.22.5" name="generator"/>
<link href="https://ec.europa.eu/eurostat/estat-theme/images/favicon.ico" rel="shortcut icon"/>
<link href="/eurostat/statistics-explained/opensearch_desc.php" rel="search" title="Statistics Explained (en)" type="application/opensearchdescription+xml"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="/eurostat/statistics-explained/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Statistics Explained Atom feed" type="application/atom+xml"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=ext.rtlcite&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=mediawiki.legacy.shared&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=skins.statexpflat&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=site&amp;only=styles&amp;skin=statexpflat&amp;*" rel="stylesheet"/>
<style>a:lang(ar), a:lang(ckb), a:lang(kk-arab), a:lang(mzn), a:lang(ps), a:lang(ur) { text-decoration: none; }</style>
<script src="https://ec.europa.eu/eurostat/statistics-explained/load.php?debug=true&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=statexpflat&amp;*"></script>
<script>if(window.mw){
mw.config.set( {
    "wgCanonicalNamespace": "Glossary",
    "wgCanonicalSpecialPageName": false,
    "wgNamespaceNumber": 100,
    "wgPageName": "Glossary:Country_codes",
    "wgTitle": "Country codes",
    "wgCurRevisionId": 512615,
    "wgRevisionId": 512615,
    "wgArticleId": 1994,
    "wgIsArticle": true,
    "wgIsRedirect": false,
    "wgAction": "view",
    "wgUserName": null,
    "wgUserGroups": [
        "*"
    ],
    "wgCategories": [
        "Geography glossary",
        "Glossary"
    ],
    "wgBreakFrames": false,
    "wgPageContentLanguage": "en",
    "wgPageContentModel": "wikitext",
    "wgSeparatorTransformTable": [
        "",
        ""
    ],
    "wgDigitTransformTable": [
        "",
        ""
    ],
    "wgDefaultDateFormat": "dmy",
    "wgMonthNames": [
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
    "wgMonthNamesShort": [
        "",
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
    ],
    "wgRelevantPageName": "Glossary:Country_codes",
    "wgIsProbablyEditable": false,
    "wgRestrictionEdit": [],
    "wgRestrictionMove": [],
    "wgWikiEditorEnabledModules": {
        "toolbar": true,
        "dialogs": false,
        "hidesig": true,
        "templateEditor": false,
        "templates": false,
        "preview": false,
        "previewDialog": false,
        "publish": false,
        "toc": false
    },
    "wgCategoryTreePageCategoryOptions": "{\"mode\":0,\"hideprefix\":20,\"showcount\":true,\"namespaces\":false}"
} );
}</script><script>if(window.mw){
mw.loader.implement( "user.options", function () {
mw.user.options.set( {
    "ccmeonemails": 0,
    "cols": 80,
    "date": "default",
    "diffonly": 0,
    "disablemail": 0,
    "disablesuggest": 0,
    "editfont": "default",
    "editondblclick": 0,
    "editsection": 1,
    "editsectiononrightclick": 0,
    "enotifminoredits": 0,
    "enotifrevealaddr": 0,
    "enotifusertalkpages": 1,
    "enotifwatchlistpages": 1,
    "extendwatchlist": 0,
    "fancysig": 0,
    "forceeditsummary": 0,
    "gender": "unknown",
    "hideminor": 0,
    "hidepatrolled": 0,
    "imagesize": 2,
    "justify": 0,
    "math": 6,
    "minordefault": 0,
    "newpageshidepatrolled": 0,
    "nocache": 0,
    "noconvertlink": 0,
    "norollbackdiff": 0,
    "numberheadings": 0,
    "previewonfirst": 0,
    "previewontop": 1,
    "rcdays": 7,
    "rclimit": 50,
    "rememberpassword": 0,
    "rows": 25,
    "searchlimit": 20,
    "showhiddencats": 0,
    "shownumberswatching": 1,
    "showtoc": 1,
    "showtoolbar": 1,
    "skin": "statexpflat",
    "stubthreshold": 0,
    "thumbsize": 2,
    "underline": 2,
    "uselivepreview": 0,
    "usenewrc": 0,
    "vector-simplesearch": 1,
    "watchcreations": 0,
    "watchdefault": 0,
    "watchdeletion": 0,
    "watchlistdays": 3,
    "watchlisthideanons": 0,
    "watchlisthidebots": 0,
    "watchlisthideliu": 0,
    "watchlisthideminor": 0,
    "watchlisthideown": 0,
    "watchlisthidepatrolled": 0,
    "watchmoves": 0,
    "wllimit": 250,
    "useeditwarning": 1,
    "prefershttps": 1,
    "flaggedrevsstable": 1,
    "usebetatoolbar": 1,
    "mathJax": true,
    "language": "en",
    "variant-gan": "gan",
    "variant-iu": "iu",
    "variant-kk": "kk",
    "variant-ku": "ku",
    "variant-shi": "shi",
    "variant-sr": "sr",
    "variant-tg": "tg",
    "variant-uz": "uz",
    "variant-zh": "zh",
    "searchNs0": true,
    "searchNs1": false,
    "searchNs2": false,
    "searchNs3": false,
    "searchNs4": false,
    "searchNs5": false,
    "searchNs6": false,
    "searchNs7": false,
    "searchNs8": false,
    "searchNs9": false,
    "searchNs10": false,
    "searchNs11": false,
    "searchNs12": false,
    "searchNs13": false,
    "searchNs14": false,
    "searchNs15": false,
    "searchNs100": false,
    "searchNs101": false,
    "searchNs104": false,
    "searchNs105": false,
    "searchNs108": false,
    "searchNs110": false,
    "searchNs111": false,
    "searchNs112": false,
    "searchNs113": false,
    "searchNs114": false,
    "searchNs120": false,
    "searchNs121": false,
    "searchNs122": false,
    "searchNs123": false,
    "searchNs124": false,
    "searchNs125": false,
    "searchNs126": false,
    "searchNs127": false,
    "searchNs128": false,
    "searchNs129": false,
    "searchNs130": false,
    "searchNs131": false,
    "searchNs132": false,
    "searchNs133": false,
    "searchNs134": false,
    "searchNs135": false,
    "searchNs154": false,
    "searchNs155": false,
    "variant": "en"
} );
}, {}, {} );
}</script>
<script>if(window.mw){
mw.loader.implement( "user.tokens", function () {
mw.user.tokens.set( {
    "editToken": "+\\",
    "patrolToken": false,
    "watchToken": false
} );
}, {}, {} );
}</script>
<script>if(window.mw){
mw.loader.load(["mediawiki.page.startup","mediawiki.legacy.wikibits","mediawiki.legacy.ajax"]);
}</script>
<link href="/eurostat/statistics-explained/extensions/EditWarning/style.css" rel="stylesheet" type="text/css"/>
<script src="/eurostat/statistics-explained/extensions/StatexpVislet/StatexpVislet.js"></script><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/statexpflat.css" rel="stylesheet"/><link href="/eurostat/statistics-explained/skins/statexpflat/css/statexpflat-grid.css" rel="stylesheet"/>
<script src="/eurostat/statistics-explained/skins/statexpflat/js/modernizr.custom.36138.js"></script>
<script src="/eurostat/statistics-explained/skins/statexpflat/js/css3-mediaqueries.js"></script><!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
			  <script src="/eurostat/statistics-explained/skins/statexpflat/js/html5shiv.min.js"></script>
			  <script src="/eurostat/statistics-explained/skins/statexpflat/js/respond.min.js"></script>
			<![endif]--></head>
<body class="mediawiki ltr sitedir-ltr ns-100 ns-subject page-Glossary_Country_codes skin-statexpflat action-view">
<!--

                <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

-->
<div class="container">
<div class="header" id="se-header">
<div class="grey-stripe"></div>
<div class="flag hidden-xs hidden-sm"></div>
<div class="flag-mobile hidden-md hidden-lg"></div>
<ul class="login list-inline hidden-xs hidden-sm">
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li><a accesskey="o" href="/eurostat/statistics-explained/index.php?title=Special:UserLogin&amp;returnto=Glossary%3ACountry+codes" title="Login is required to edit (reserved for Eurostat and accredited contributors)">log in</a></li>
<li class="login-icon"></li>
</ul>
<div class="heading">
<!--<div class="statexp-small hidden-lg hidden-md">Statistics Explained</div>-->
<div class="lighthouse articles visible-lg-block"></div>
<div class="alert alert-th3" style="

       position: absolute;
    z-index: 150;
    width: 300px;
    top: 60px;
    margin-left: 200px;
    background-color: #FF7900;
    color: #f9f9f9;
    font-weight: bolder;
    font-size: 12px;

"><p>Try the new automatic translation by clicking on the blue icon “Translate” up in the right corner of the article!</p></div>
<div class="links hidden-xs hidden-sm">
<ul class="list-inline">
<li class="lang-selector hidden-xs hidden-sm">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" id="lang-selector" type="button">
<a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes">English</a> <span class="caret"></span>
</button>
<ul aria-labelledby="dLabel" class="dropdown-menu" role="menu">
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes/de">Deutsch</a></li>
<li><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes/fr">français</a></li>
</ul>
</div>
</li>
</ul>
</div>
<!----
		<div class="eurostat">eurostat</div>
		<div class="statexp">Statistics Explained</div>
		<!---->
<a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page"><div class="statexptitle"></div></a>
<div class="mobile-header-buttons hidden-md hidden-lg">
<button class="bt-open" id="mobile-menu-button">
<span class="glyphicon glyphicon-align-justify icon-show"></span>
<span class="glyphicon glyphicon-remove icon-hide"></span>
</button>
<button class="bt-open" id="mobile-search-button">
<span class="glyphicon glyphicon-search icon-show"></span>
<span class="glyphicon glyphicon-remove icon-hide"></span>
</button>
</div>
<!-- -->
<div class="search-box hidden-xs hidden-sm">
<form action="/eurostat/statistics-explained/index.php" class="form-inline" id="searchform">
<input name="title" type="hidden" value="Special:Search"/>
<div class="form-group">
<div class="input-group">
<input accesskey="f" class="form-control search-field" id="searchInput" name="search" placeholder="Search" title="Search Statistics Explained [f]" type="search"/> <span class="input-group-btn">
<button class="btn search-btn search-general" id="mw-searchButton" type="submit">
<span aria-hidden="true" class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</div>
</form>
</div>
</div>
<div class="row hidden-xs hidden-sm">
<div class="col-lg-12" id="menu-bar-container">
<div class="row menu-bar-container">
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>
<ul aria-labelledby="Navigation" class="dropdown-menu">
<li id="n-Home"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page">Main page</a></li>
<li id="n-Statistical-themes"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Statistical_themes">Statistical themes</a></li>
<li id="n-Glossary"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Thematic_glossaries">Glossary</a></li>
<li id="n-Categories"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Special:Categories">Categories</a></li>
<li id="n-Statistics-4-beginners"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Beginners:Statistics_4_beginners">Statistics 4 beginners</a></li>
<li id="n-Tutorials"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li id="n-help"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
<li id="n-Eurostat-home"><a href="http://ec.europa.eu/eurostat/" rel="nofollow">Eurostat home</a></li>
<li id="n-Contact-Eurostat"><a href="http://ec.europa.eu/eurostat/help/support" rel="nofollow">Contact Eurostat</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-m-onlinepub" type="button">
               Online publications              <span class="caret"></span>
</button>
<ul aria-labelledby="Online publications" class="dropdown-menu">
<li id="n-Regional-yearbook"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Eurostat_regional_yearbook">Regional yearbook</a></li>
<li id="n-The-EU-in-the-world"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world">The EU in the world</a></li>
<li id="n-Other-publications"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Online publications">Full list</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-TOOLBOX" type="button">
Tools               <span class="caret"></span>
</button>
<ul aria-labelledby="" class="dropdown-menu">
<li id="t-whatlinkshere"><a accesskey="j" href="/eurostat/statistics-explained/index.php?title=Special:WhatLinksHere/Glossary:Country_codes" title="A list of all wiki pages that link here [j]">What links here</a></li> <li id="t-specialpages"><a accesskey="q" href="/eurostat/statistics-explained/index.php?title=Special:SpecialPages" title="A list of all special pages [q]">Special pages</a></li> </ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row hidden-md hidden-lg">
<div class="col-sm-12 col-xs-12 mobile-search">
<div class="search-box search-box-mobile hidden-md hidden-lg">
<form action="/eurostat/statistics-explained/index.php" class="form-inline" id="searchform">
<input name="title" type="hidden" value="Special:Search"/>
<div class="form-group">
<div class="input-group">
<input accesskey="f" class="form-control search-field" id="searchInput" name="search" placeholder="Search" title="Search Statistics Explained [f]" type="search"/> <span class="input-group-btn">
<button class="btn search-btn search-general" id="mw-searchButton" type="submit">
<span aria-hidden="true" class="glyphicon glyphicon-search"></span>
</button>
</span>
</div>
</div>
</form>
</div>
</div>
<div class="col-sm-12 col-xs-12 mobile-menu">
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>
<ul aria-labelledby="Navigation" class="dropdown-menu">
<li id="n-Home"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Main_Page">Main page</a></li>
<li id="n-Statistical-themes"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Statistical_themes">Statistical themes</a></li>
<li id="n-Glossary"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Thematic_glossaries">Glossary</a></li>
<li id="n-Categories"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Special:Categories">Categories</a></li>
<li id="n-Statistics-4-beginners"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Beginners:Statistics_4_beginners">Statistics 4 beginners</a></li>
<li id="n-Tutorials"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Tutorial:Help_for_readers
">Tutorials</a></li>
<li id="n-help"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Help:Contents" rel="nofollow" title="The place to find out">Help</a></li>
<li id="n-Eurostat-home"><a href="http://ec.europa.eu/eurostat/" rel="nofollow">Eurostat home</a></li>
<li id="n-Contact-Eurostat"><a href="http://ec.europa.eu/eurostat/help/support" rel="nofollow">Contact Eurostat</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-m-onlinepub" type="button">
               Online publications              <span class="caret"></span>
</button>
<ul aria-labelledby="Online publications" class="dropdown-menu">
<li id="n-Regional-yearbook"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Eurostat_regional_yearbook">Regional yearbook</a></li>
<li id="n-The-EU-in-the-world"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world">The EU in the world</a></li>
<li id="n-Other-publications"><a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Online publications">Full list</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-TOOLBOX" type="button">
Tools               <span class="caret"></span>
</button>
<ul aria-labelledby="" class="dropdown-menu">
<li id="t-whatlinkshere"><a accesskey="j" href="/eurostat/statistics-explained/index.php?title=Special:WhatLinksHere/Glossary:Country_codes" title="A list of all wiki pages that link here [j]">What links here</a></li> <li id="t-specialpages"><a accesskey="q" href="/eurostat/statistics-explained/index.php?title=Special:SpecialPages" title="A list of all special pages [q]">Special pages</a></li> </ul>
</div>
</div>
</div>
</div>
<!--END HEADER BEGIN PAGE-->
<!----
<div class="onerow">
<!---->
<div class="row content-row">
<!-- BEGIN LSF -->
<!-- -->
<div class="hidden-md hidden-lg hidden-xs hidden-sm sidebar content-col">
<!----
		<div class="col2 sidebar">
		<!---->
<div class="col-lg-4 col-md-4 head-menu-bar">
<div class="dropdown">
<button aria-expanded="false" aria-haspopup="true" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="p-navigation" type="button">
               Navigation              <span class="caret"></span>
</button>

In [11]:
all_tables = soup.find_all('table')

all_tables[0]

<table border="1" cellpadding="2" cellspacing="0" style="vertical-align:top;background-color:#f5faff" width="80%">
<tr>
<td>Belgium
</td>
<td>(BE)
</td>
<td>Greece
</td>
<td>(EL)
</td>
<td>Lithuania
</td>
<td>(LT)
</td>
<td>Portugal
</td>
<td>(PT)
</td></tr>
<tr>
<td>Bulgaria
</td>
<td>(BG)
</td>
<td>Spain
</td>
<td>(ES)
</td>
<td>Luxembourg
</td>
<td>(LU)
</td>
<td>Romania
</td>
<td>(RO)
</td></tr>
<tr>
<td>Czechia
</td>
<td>(CZ)
</td>
<td>France
</td>
<td>(FR)
</td>
<td>Hungary
</td>
<td>(HU)
</td>
<td>Slovenia
</td>
<td>(SI)
</td></tr>
<tr>
<td>Denmark
</td>
<td>(DK)
</td>
<td>Croatia
</td>
<td>(HR)
</td>
<td>Malta
</td>
<td>(MT)
</td>
<td>Slovakia
</td>
<td>(SK)
</td></tr>
<tr>
<td>Germany
</td>
<td>(DE)
</td>
<td>Italy
</td>
<td>(IT)
</td>
<td>Netherlands
</td>
<td>(NL)
</td>
<td>Finland
</td>
<td>(FI)
</td></tr>
<tr>
<td>Estonia
</td>
<td>(EE)
</td>
<td>Cyprus
</td>
<td>(CY)
</td>
<td>Austria
</td>
<td>(AT)
</td>
<td>Sweden
</td>
<td>(SE)
</td></tr>
<tr>
<td>Ireland
</td>
<td>(IE)
</td>
<td>Latvia
</td>
<td>(LV)
</td>
<td>Poland
</td>
<td>(PL)
</td></tr></table>

In [12]:
my_list_tables = []

for table in all_tables:
    table_rows = table.find_all('tr')
    for tr in table_rows:
        td = tr.find_all('td')
        for tr in td:
            my_list_tables.append(tr.text)
        

my_list_tables

['Belgium\n',
 '(BE)\n',
 'Greece\n',
 '(EL)\n',
 'Lithuania\n',
 '(LT)\n',
 'Portugal\n',
 '(PT)\n',
 'Bulgaria\n',
 '(BG)\n',
 'Spain\n',
 '(ES)\n',
 'Luxembourg\n',
 '(LU)\n',
 'Romania\n',
 '(RO)\n',
 'Czechia\n',
 '(CZ)\n',
 'France\n',
 '(FR)\n',
 'Hungary\n',
 '(HU)\n',
 'Slovenia\n',
 '(SI)\n',
 'Denmark\n',
 '(DK)\n',
 'Croatia\n',
 '(HR)\n',
 'Malta\n',
 '(MT)\n',
 'Slovakia\n',
 '(SK)\n',
 'Germany\n',
 '(DE)\n',
 'Italy\n',
 '(IT)\n',
 'Netherlands\n',
 '(NL)\n',
 'Finland\n',
 '(FI)\n',
 'Estonia\n',
 '(EE)\n',
 'Cyprus\n',
 '(CY)\n',
 'Austria\n',
 '(AT)\n',
 'Sweden\n',
 '(SE)\n',
 'Ireland\n',
 '(IE)\n',
 'Latvia\n',
 '(LV)\n',
 'Poland\n',
 '(PL)\n',
 ' Iceland\n',
 ' (IS)\n',
 '\n',
 ' Norway\n',
 ' (NO)\n',
 ' Liechtenstein\n',
 ' (LI)\n',
 '\n',
 ' Switzerland\n',
 ' (CH)\n',
 ' United Kingdom\n',
 ' (UK)\n',
 '\n',
 ' Montenegro\n',
 ' (ME)\n',
 ' North Macedonia\n',
 ' (MK)\n',
 ' Albania\n',
 ' (AL)\n',
 'Serbia\n',
 ' (RS)\n',
 ' Turkey\n',
 ' (TR)\n',
 ' Bosnia and Herzegovina\n',
 ' (BA)\n',
 ' Kosovo*\n',
 ' (XK[1])\n',
 ' Armenia\n',
 ' (AM)\n',
 '\n',
 ' Belarus\n',
 ' (BY)\n',
 '\n',
 ' Georgia\n',
 ' (GE)\n',
 ' Azerbaijan\n',
 ' (AZ)\n',
 '\n',
 ' Moldova\n',
 ' (MD)\n',
 '\n',
 ' Ukraine\n',
 ' (UA)\n',
 ' Algeria\n',
 ' (DZ)\n',
 '\n',
 ' Lebanon\n',
 ' (LB)\n',
 '\n',
 ' Syria\n',
 ' (SY)\n',
 ' Egypt\n',
 ' (EG)\n',
 '\n',
 ' Libya\n',
 ' (LY)\n',
 '\n',
 ' Tunisia\n',
 ' (TN)\n',
 ' Israel\n',
 ' (IL)\n',
 '\n',
 ' Morocco\n',
 ' (MA)\n',
 '\n',
 ' \xa0\n',
 ' \xa0\n',
 ' Jordan\n',
 ' (JO)\n',
 '\n',
 ' Palestine [2]\n',
 ' (PS)\n',
 '\n',
 ' \xa0\n',
 ' \xa0\n',
 ' Russia\n',
 ' (RU)\n',
 'Argentina\n',
 '(AR)\n',
 '\n',
 'China (except Hong Kong)\n',
 '(CN_X_HK)\n',
 '\n',
 'Mexico\n',
 '(MX)\n',
 '\n',
 'South Africa\n',
 '(ZA)\n',
 'Australia\n',
 '(AU)\n',
 '\n',
 'Hong Kong\n',
 '(HK)\n',
 '\n',
 'Nigeria\n',
 '(NG)\n',
 '\n',
 'South Korea\n',
 '(KR)\n',
 'Brazil\n',
 '(BR)\n',
 '\n',
 'India\n',
 '(IN)\n',
 '\n',
 'New Zealand\n',
 '(NZ)\n',
 '\n',
 'Taiwan\n',
 '(TW)\n',
 'Canada\n',
 '(CA)\n',
 '\n',
 'Japan\n',
 '(JP)\n',
 '\n',
 'Singapore\n',
 '(SG)\n',
 '\n',
 'United States\n',
 '(US)\n']

In [13]:
#Drop \n from my list_tables and cleaning

converted_list = []

for element in my_list_tables:
    converted_list.append(element.strip())

converted_list = list(filter(None, converted_list))

converted_list

['Belgium',
 '(BE)',
 'Greece',
 '(EL)',
 'Lithuania',
 '(LT)',
 'Portugal',
 '(PT)',
 'Bulgaria',
 '(BG)',
 'Spain',
 '(ES)',
 'Luxembourg',
 '(LU)',
 'Romania',
 '(RO)',
 'Czechia',
 '(CZ)',
 'France',
 '(FR)',
 'Hungary',
 '(HU)',
 'Slovenia',
 '(SI)',
 'Denmark',
 '(DK)',
 'Croatia',
 '(HR)',
 'Malta',
 '(MT)',
 'Slovakia',
 '(SK)',
 'Germany',
 '(DE)',
 'Italy',
 '(IT)',
 'Netherlands',
 '(NL)',
 'Finland',
 '(FI)',
 'Estonia',
 '(EE)',
 'Cyprus',
 '(CY)',
 'Austria',
 '(AT)',
 'Sweden',
 '(SE)',
 'Ireland',
 '(IE)',
 'Latvia',
 '(LV)',
 'Poland',
 '(PL)',
 'Iceland',
 '(IS)',
 'Norway',
 '(NO)',
 'Liechtenstein',
 '(LI)',
 'Switzerland',
 '(CH)',
 'United Kingdom',
 '(UK)',
 'Montenegro',
 '(ME)',
 'North Macedonia',
 '(MK)',
 'Albania',
 '(AL)',
 'Serbia',
 '(RS)',
 'Turkey',
 '(TR)',
 'Bosnia and Herzegovina',
 '(BA)',
 'Kosovo*',
 '(XK[1])',
 'Armenia',
 '(AM)',
 'Belarus',
 '(BY)',
 'Georgia',
 '(GE)',
 'Azerbaijan',
 '(AZ)',
 'Moldova',
 '(MD)',
 'Ukraine',
 '(UA)',
 'Algeria',
 '(DZ)',
 'Lebanon',
 '(LB)',
 'Syria',
 '(SY)',
 'Egypt',
 '(EG)',
 'Libya',
 '(LY)',
 'Tunisia',
 '(TN)',
 'Israel',
 '(IL)',
 'Morocco',
 '(MA)',
 'Jordan',
 '(JO)',
 'Palestine [2]',
 '(PS)',
 'Russia',
 '(RU)',
 'Argentina',
 '(AR)',
 'China (except Hong Kong)',
 '(CN_X_HK)',
 'Mexico',
 '(MX)',
 'South Africa',
 '(ZA)',
 'Australia',
 '(AU)',
 'Hong Kong',
 '(HK)',
 'Nigeria',
 '(NG)',
 'South Korea',
 '(KR)',
 'Brazil',
 '(BR)',
 'India',
 '(IN)',
 'New Zealand',
 '(NZ)',
 'Taiwan',
 '(TW)',
 'Canada',
 '(CA)',
 'Japan',
 '(JP)',
 'Singapore',
 '(SG)',
 'United States',
 '(US)']

In [14]:
# Converting list to dictionary

titles = []
codes = []

my_dict_tables = {"codes": codes, "titles": titles}


for item in converted_list:
    if "(" in item and " " not in item:
        codes.append(item)
    else:
        titles.append(item)

my_dict_tables['codes']
my_dict_tables['titles']

['Belgium',
 'Greece',
 'Lithuania',
 'Portugal',
 'Bulgaria',
 'Spain',
 'Luxembourg',
 'Romania',
 'Czechia',
 'France',
 'Hungary',
 'Slovenia',
 'Denmark',
 'Croatia',
 'Malta',
 'Slovakia',
 'Germany',
 'Italy',
 'Netherlands',
 'Finland',
 'Estonia',
 'Cyprus',
 'Austria',
 'Sweden',
 'Ireland',
 'Latvia',
 'Poland',
 'Iceland',
 'Norway',
 'Liechtenstein',
 'Switzerland',
 'United Kingdom',
 'Montenegro',
 'North Macedonia',
 'Albania',
 'Serbia',
 'Turkey',
 'Bosnia and Herzegovina',
 'Kosovo*',
 'Armenia',
 'Belarus',
 'Georgia',
 'Azerbaijan',
 'Moldova',
 'Ukraine',
 'Algeria',
 'Lebanon',
 'Syria',
 'Egypt',
 'Libya',
 'Tunisia',
 'Israel',
 'Morocco',
 'Jordan',
 'Palestine [2]',
 'Russia',
 'Argentina',
 'China (except Hong Kong)',
 'Mexico',
 'South Africa',
 'Australia',
 'Hong Kong',
 'Nigeria',
 'South Korea',
 'Brazil',
 'India',
 'New Zealand',
 'Taiwan',
 'Canada',
 'Japan',
 'Singapore',
 'United States']

In [15]:
df_countries = pd.DataFrame.from_dict(my_dict_tables)

df_countries

   codes         titles
0   (BE)        Belgium
1   (EL)         Greece
2   (LT)      Lithuania
3   (PT)       Portugal
4   (BG)       Bulgaria
..   ...            ...
67  (TW)         Taiwan
68  (CA)         Canada
69  (JP)          Japan
70  (SG)      Singapore
71  (US)  United States

[72 rows x 2 columns]

In [16]:
df_countries['codes'] = df_countries['codes'].map(lambda x: x.lstrip('(').rstrip(')'))

df_countries

   codes         titles
0     BE        Belgium
1     EL         Greece
2     LT      Lithuania
3     PT       Portugal
4     BG       Bulgaria
..   ...            ...
67    TW         Taiwan
68    CA         Canada
69    JP          Japan
70    SG      Singapore
71    US  United States

[72 rows x 2 columns]

In [17]:
df_to_dict_countries = df_countries.to_dict('records')

df_to_dict_countries

[{'codes': 'BE', 'titles': 'Belgium'},
 {'codes': 'EL', 'titles': 'Greece'},
 {'codes': 'LT', 'titles': 'Lithuania'},
 {'codes': 'PT', 'titles': 'Portugal'},
 {'codes': 'BG', 'titles': 'Bulgaria'},
 {'codes': 'ES', 'titles': 'Spain'},
 {'codes': 'LU', 'titles': 'Luxembourg'},
 {'codes': 'RO', 'titles': 'Romania'},
 {'codes': 'CZ', 'titles': 'Czechia'},
 {'codes': 'FR', 'titles': 'France'},
 {'codes': 'HU', 'titles': 'Hungary'},
 {'codes': 'SI', 'titles': 'Slovenia'},
 {'codes': 'DK', 'titles': 'Denmark'},
 {'codes': 'HR', 'titles': 'Croatia'},
 {'codes': 'MT', 'titles': 'Malta'},
 {'codes': 'SK', 'titles': 'Slovakia'},
 {'codes': 'DE', 'titles': 'Germany'},
 {'codes': 'IT', 'titles': 'Italy'},
 {'codes': 'NL', 'titles': 'Netherlands'},
 {'codes': 'FI', 'titles': 'Finland'},
 {'codes': 'EE', 'titles': 'Estonia'},
 {'codes': 'CY', 'titles': 'Cyprus'},
 {'codes': 'AT', 'titles': 'Austria'},
 {'codes': 'SE', 'titles': 'Sweden'},
 {'codes': 'IE', 'titles': 'Ireland'},
 {'codes': 'LV', 'titles': 'Latvia'},
 {'codes': 'PL', 'titles': 'Poland'},
 {'codes': 'IS', 'titles': 'Iceland'},
 {'codes': 'NO', 'titles': 'Norway'},
 {'codes': 'LI', 'titles': 'Liechtenstein'},
 {'codes': 'CH', 'titles': 'Switzerland'},
 {'codes': 'UK', 'titles': 'United Kingdom'},
 {'codes': 'ME', 'titles': 'Montenegro'},
 {'codes': 'MK', 'titles': 'North Macedonia'},
 {'codes': 'AL', 'titles': 'Albania'},
 {'codes': 'RS', 'titles': 'Serbia'},
 {'codes': 'TR', 'titles': 'Turkey'},
 {'codes': 'BA', 'titles': 'Bosnia and Herzegovina'},
 {'codes': 'XK[1]', 'titles': 'Kosovo*'},
 {'codes': 'AM', 'titles': 'Armenia'},
 {'codes': 'BY', 'titles': 'Belarus'},
 {'codes': 'GE', 'titles': 'Georgia'},
 {'codes': 'AZ', 'titles': 'Azerbaijan'},
 {'codes': 'MD', 'titles': 'Moldova'},
 {'codes': 'UA', 'titles': 'Ukraine'},
 {'codes': 'DZ', 'titles': 'Algeria'},
 {'codes': 'LB', 'titles': 'Lebanon'},
 {'codes': 'SY', 'titles': 'Syria'},
 {'codes': 'EG', 'titles': 'Egypt'},
 {'codes': 'LY', 'titles': 'Libya'},
 {'codes': 'TN', 'titles': 'Tunisia'},
 {'codes': 'IL', 'titles': 'Israel'},
 {'codes': 'MA', 'titles': 'Morocco'},
 {'codes': 'JO', 'titles': 'Jordan'},
 {'codes': 'PS', 'titles': 'Palestine [2]'},
 {'codes': 'RU', 'titles': 'Russia'},
 {'codes': 'AR', 'titles': 'Argentina'},
 {'codes': 'CN_X_HK', 'titles': 'China (except Hong Kong)'},
 {'codes': 'MX', 'titles': 'Mexico'},
 {'codes': 'ZA', 'titles': 'South Africa'},
 {'codes': 'AU', 'titles': 'Australia'},
 {'codes': 'HK', 'titles': 'Hong Kong'},
 {'codes': 'NG', 'titles': 'Nigeria'},
 {'codes': 'KR', 'titles': 'South Korea'},
 {'codes': 'BR', 'titles': 'Brazil'},
 {'codes': 'IN', 'titles': 'India'},
 {'codes': 'NZ', 'titles': 'New Zealand'},
 {'codes': 'TW', 'titles': 'Taiwan'},
 {'codes': 'CA', 'titles': 'Canada'},
 {'codes': 'JP', 'titles': 'Japan'},
 {'codes': 'SG', 'titles': 'Singapore'},
 {'codes': 'US', 'titles': 'United States'}]

In [18]:
country_codes = working_dataframe['country_code'].to_list()
country_titles = []

# Add missing countries to dictionary
df_to_dict_countries.append({'codes': 'GB', 'titles': 'United Kingdom'})
df_to_dict_countries.append({'codes': 'GR', 'titles': 'Greece'})

for code in country_codes:
    for row in df_to_dict_countries:
        if code == row['codes']:
            country_titles.append(row['titles'])

In [46]:
working_dataframe['country'] = country_titles

working_dataframe.drop(columns = ['normalized_job_code','country_code'])

<ipython-input-46-5c29223ea284>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  working_dataframe['country'] = country_titles

KeyError: "['normalized_job_code' 'country_code'] not found in axis"

In [47]:
final_df = working_dataframe[['country', 'title', 'gender','age']]

In [44]:
final_df

       country                              title  gender  age
0      Austria                               None    Male   65
1      Austria  Automatic Data Processing Planner    Male   61
2      Austria                               None    Male   36
3      Austria                   Data Coordinator    Male   49
4      Austria                 Database Developer  Female   45
...        ...                                ...     ...  ...
9644  Slovakia           Data Warehouse Developer  Female   41
9645  Slovakia                   Database Manager    Male   57
9646  Slovakia                               None    Male   32
9647  Slovakia                       Data Officer    Male   51
9648  Slovakia                     Data Scientist  Female   55

[9649 rows x 4 columns]

In [45]:
agg_df = final_df.groupby('gender').agg('gender')
                                             
agg_df